### ISSUE TITLE
Events not rendered between "next" & "previous" week navigation

### ISSUE THREAD

**Issue by srikanthraob** [themouette/jquery-week-calendar#165] opened 2012-12-02 15:19 UTC
Newly created events are not rendered once we navigate to "next week" or "previous week". (Top left) 
Steps to reproduce:
1. Go to "Next week" clicking on ">" button
2. Create New event on one of the day
3. Go to "Previous week" clicking on "<" button
4. Come back to "Next week" click on ">" button
5. You won't find the even created in step 2.

I am not sure, if this is already fixed but I am able to reproduce this on the demo URL as well 
http://themouette.github.com/jquery-week-calendar/weekcalendar.html

**Comment by shakerlxxv** [comment] 2012-12-02 22:24
srikanthraob, it seems to me this behavior you're describing is the expected behavior, not a bug. the demos do not provide any backend storage for newly created events, this is left to you the developer to determine how to best store your event data.

**Comment by K-Phoen** [comment] 2012-12-03 14:36
What shakerlxxv said is correct. New events are not persisted in demos.

I close this issue as it's more a "not implemented" case.

**Closed as completed by K-Phoen** 2012-12-03 14:36 UTC

**Comment by srikanthraob** [comment] 2012-12-03 15:14
Thank you, All. I noticed it in my implemented code as well, where I persist & get back the values... I will debug more in terms of what is happening.
