### ISSUE TITLE
calEvent id undefined

### ISSUE THREAD

**Issue by r0no** [themouette/jquery-week-calendar#93] opened 2011-10-27 12:55 UTC
While creating the calendar event and moving the event with drag and drop, it results in "calEvent id undefined" error on 1559 row in jquery.weekcalendar.js file if you remove the event after moving it. Here's a code how to replicate it f.e. in weekcalendar_demo_4.html file. Just replace the eventDrop with these lines.

<pre><code>
eventDrop : function(calEvent, $event) {
                displayMessage("<strong>Moved Event</strong><br/>Start: " + calEvent.start + "<br/>End: " + calEvent.end);
                $('#calendar').weekCalendar("removeEvent", calEvent.id);
},</code></pre>

**Comment by robotdan** [comment] 2011-10-27 14:08
I think this is working as designed.

In weekcalendar_demo_4.html, the initial events are created with an id, start, end and title.

<pre>
    var eventData = {
        events : [
           {"id":1, "start": new Date(year, month, day, 12), "end": new Date(year, month, day, 13, 35),"title":"Lunch with Mike"},
           {"id":2, "start": new Date(year, month, day, 14), "end": new Date(year, month, day, 14, 45),"title":"Dev Meeting"},
           {"id":3, "start": new Date(year, month, day + 1, 18), "end": new Date(year, month, day + 1, 18, 45),"title":"Hair cut"},
           {"id":4, "start": new Date(year, month, day - 1, 8), "end": new Date(year, month, day - 1, 9, 30),"title":"Team breakfast"},
           {"id":5, "start": new Date(year, month, day + 1, 14), "end": new Date(year, month, day + 1, 16),"title":"Product showcase"},
           {"id":5, "start": new Date(year, month, day + 1, 15), "end": new Date(year, month, day + 1, 17),"title":"Overlay event"}
        ]
    };
</pre>


In the eventNew handler, by default it is not adding an id to the calEvent created, you'd need to add that capability.

<pre>
eventNew : function(calEvent, $event) {
                displayMessage("<strong>Added event</strong><br/>Start: " + calEvent.start + "<br/>End: " + calEvent.end);
                alert("You've added a new event. You would capture this event, add the logic for creating a new event with your own fields, data and whatever backend persistence you require.");
            }
</pre>


Try adding the following line to the eventNew handler - or something similar to generate a unique id for the newly created event.

<pre>
calEvent.id = Math.floor(Math.random() * 900000000) + 100000;
</pre>

**Comment by r0no** [comment] 2011-10-28 00:11
Thank you for your help. I actually gave the event an id before and it still didn't work. I modified the displayMessage and added id printing there, and it would display it normally.

<pre>
eventDrop : function(calEvent, $event) {
                displayMessage("Moved Event " + calEvent.id + " Start: " + calEvent.start + "End: " + calEvent.end);
                $('#calendar').weekCalendar("removeEvent", calEvent.id);
},
</pre>


It's failing after removeEvent has been launched.

**Comment by robotdan** [comment] 2011-10-28 14:27
I hadn't tried removing the event in the eventDrop handler.

Is this what you are seeing? 

<pre>
Uncaught TypeError: Cannot read property 'start' of undefined
</pre>


Do you have to do it there?  

It seems the calendar doesn't expect you to try to remove the event in that location. 
I can see in the code how this would happen.

Is this just for testing, or do you really want to the delete the event when a user drags and drops an event on the calendar?

**Comment by twaggs** [comment] 2011-10-28 14:36
I'm actually experiencing something similar. Is there a better way to handle validation on the drop and "undoing" the move if validation fails? I tried just setting the calEvent details and updating the item, but received the same errors mentioned here when working with the event later.

**Comment by robotdan** [comment] 2011-10-28 14:51
If you want to undo the move action based upon some validation you'd like to do, you could just change the start and end time of the new object like this:

<pre>
eventDrop: function(newCalEvent, oldCalEvent, element) {
        if (!validate) {              
             newCalEvent.start = oldCalEvent.start;
             newCalEvent.end = oldCalEvent.end;           
         }   
 }
</pre>

**Comment by twaggs** [comment] 2011-10-28 15:03
Thanks for your help. My problem was calling updateEvent after setting the start/end.

**Comment by K-Phoen** [comment] 2012-04-27 11:36
As the issue seems to be solved, I close it. Feel free to reopen it if needed.

**Closed as completed by K-Phoen** 2012-04-27 11:36 UTC
