### ISSUE TITLE
Use of minDate and maxDate.

### ISSUE THREAD

**Issue by cpauya** [themouette/jquery-week-calendar#35] opened 2011-02-17 09:26 UTC
Hi,

Thanks for this wonderful jQuery plugin.  I need help in using the minDate and maxDate options:

I set the values to:
    ....
    var minDate = new Date(2011,01,11,12,00,000);
    var maxDate = new Date(2011,01,20,12,00,000);
    ....
    var $calendar = $('#calendar').weekCalendar({
        minDate: minDate, 
        maxDate: maxDate,
    ....

However, when I click on the Previous, Today, and Next buttons it does not work as expected.  

The calendar behaves erratically, either:
    \* it moves the days backwards (whatever button I click)
    \* it moves the days forwards (whatever button I click)

I may be doing something wrong here, tried looking at the wiki at https://github.com/themouette/jquery-week-calendar/wiki/Script-options and it's not documented there too.

Thanks in advance for the help.

P.S.:
    \* I already saw issue #8 but it does not mention how to limit the start and end dates. https://github.com/themouette/jquery-week-calendar/issues/closed#issue/8
    \* I also saw issue #33 https://github.com/themouette/jquery-week-calendar/issuesearch?state=open&q=mindate#issue/33

**Comment by dittodhole** [comment] 2011-02-17 09:37
both next- and prev-button call `prev()` or `next()`, which have those in first line:

```
if (this._startOnFirstDayOfWeek()){
    return this.prevWeek();
}
```

and

```
if(this._startOnFirstDayOfWeek()){
    return this.nextWeek();
}
```

neither `prevWeek()` nor `nextWeek()` checks against the range-constraint of `minDate` and `maxDate` currently.

the `_startOnFirstDayOfWeek()` calls `startOnFirstDayOfWeek()` by default:

```
startOnFirstDayOfWeek : function(calendar) {
    return $(calendar).weekCalendar('option', 'daysToShow') >= 5;
}
```

so, my question: what is your value of `daysToShow`?

**Comment by cpauya** [comment] 2011-02-17 09:39
Thanks for the quick reply, I have `daysToShow: 3`

**Comment by dittodhole** [comment] 2011-02-17 09:41
can you support a demo somewhere?

**Comment by cpauya** [comment] 2011-02-17 09:43
Sorry, I accidentally closed this issue but the issue still stands.

No, i'm still on local devt so I can't show you something.

**Comment by dittodhole** [comment] 2011-02-17 09:59
ahh ... there's a solution :)

does this look like yours: http://jsfiddle.net/QdCWc/3/

please adapt the code that it matches yours, so i can do a debug :)

**Comment by cpauya** [comment] 2011-02-17 10:07
Hey this is pretty neat, thanks! :)

I added the following codes on line 7 of "Javascript" section:
    minDate = new Date(2011,01,11,12,00,000);
    maxDate = new Date(2011,01,20,12,00,000);

Now the buttons show the "bug" I am talking about.

**Comment by dittodhole** [comment] 2011-02-17 10:11
i've done some adaptions on my own: http://jsfiddle.net/QdCWc/5/ ...
jep ... pretty wired ...

i'll try to fix that!

**Comment by dittodhole** [comment] 2011-02-17 10:29
the reason for the wired behaviour is, that something is changing `options.minDate` and `options.maxDate` on pressing ... but i haven't found that piece of code yet :(

**Comment by dittodhole** [comment] 2011-02-17 10:43
the problem is caused by `_dateFirstDayOfWeek()` and `_dateLastDayOfWeek()`

**Comment by dittodhole** [comment] 2011-02-17 10:46
`prev()` is working again: http://jsfiddle.net/QdCWc/8/

**Comment by dittodhole** [comment] 2011-02-17 11:41
`next()` is working again: http://jsfiddle.net/QdCWc/11/

**Comment by dittodhole** [comment] 2011-02-17 11:47
bugs identified:

reference bug for `next()`:

```
var maxDate = this._cleanDate(this.options.maxDate); // line 460
```

this will keep the reference, which is adapted here:

```
maxDate.setDate(_maxDate.getDate() - this.options.daysToShow + 1); // line 461
```

proof (line 1993ff):

```
    /*
    * return a date for different representations
    */
    _cleanDate: function (d) {
        if (typeof d == 'string') {
            return Date.parse(d) || new Date(parseInt(d, 10));
        }
        if (typeof d == 'number') {
            return new Date(d);
        }
        return d;
    },
```

reference bug for `prev()`:

```
var minDate = this._cleanDate(this.options.minDate); // line 476
```

reference is adapted in:

```
this._loadCalEvents(newDate); // line 481
```

line 1876ff

```
    /*
    * returns the date on the first millisecond of the week
    */
    _dateFirstDayOfWeek: function (date) {
        var self = this;
        var midnightCurrentDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        var adjustedDate = new Date(midnightCurrentDate);
        adjustedDate.setDate(adjustedDate.getDate() - self._getAdjustedDayIndex(midnightCurrentDate));

        if (this.options.minDate !== null) {
            var minDate = this._cleanDate(this.options.minDate);
            if (adjustedDate.getTime() < minDate.getTime())
                adjustedDate = minDate;
        }
        if (this.options.maxDate !== null) {
            var maxDate = this._cleanDate(this.options.maxDate);
            _maxDate.setDate(maxDate.getDate() - this.options.daysToShow + 1);
            if (adjustedDate.getTime() > maxDate.getTime())
                adjustedDate = maxDate;
        }

        return adjustedDate;
    },

    /*
    * returns the date on the first millisecond of the last day of the week
    */
    _dateLastDayOfWeek: function (date) {
        var self = this;
        var midnightCurrentDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        var adjustedDate = new Date(midnightCurrentDate);
        var daysToAdd = (self.options.daysToShow - 1 - self._getAdjustedDayIndex(midnightCurrentDate));
        adjustedDate.setDate(adjustedDate.getDate() + daysToAdd);

        if (this.options.minDate !== null) {
            var minDate = this._cleanDate(this.options.minDate);
            minDate.setDate(minDate.getDate() + this.options.daysToShow - 1);
            if (adjustedDate.getTime() < _minDate.getTime())
                adjustedDate = minDate;
        }
        if (this.options.maxDate !== null) {
            var maxDate = this._cleanDate(this.options.maxDate);
            if (adjustedDate.getTime() > maxDate.getTime())
                adjustedDate = maxDate;
        }

        return adjustedDate;
    },
```

solution: break the references

```
var maxDate = this._cloneDate(this._cleanDate(this.options.maxDate)); // line 460
var minDate = this._cloneDate(this._cleanDate(this.options.minDate)); // line 476
```

remove line 1885-1896:

```
        if (this.options.minDate !== null) {
            var _minDate = this._cleanDate(this.options.minDate);
            if (adjustedDate.getTime() < _minDate.getTime())
                adjustedDate = _minDate;
        }
        if (this.options.maxDate !== null) {
            var _maxDate = this._cleanDate(this.options.maxDate);
            _maxDate.setDate(_maxDate.getDate() - this.options.daysToShow + 1);
            if (adjustedDate.getTime() > _maxDate.getTime())
                adjustedDate = _maxDate;
        }
```

remove line 1910-1921:

```
        if (this.options.minDate !== null) {
            var _minDate = this._cleanDate(this.options.minDate);
            _minDate.setDate(_minDate.getDate() + this.options.daysToShow - 1);
            if (adjustedDate.getTime() < _minDate.getTime())
                adjustedDate = _minDate;
        }
        if (this.options.maxDate !== null) {
            var _maxDate = this._cleanDate(this.options.maxDate);
            if (adjustedDate.getTime() > _maxDate.getTime())
                adjustedDate = _maxDate;
        }
```

i do not know if the adaption of `_dateFirstDayOfWeek()` and `_dateLastDayOfWeek()` causes any sideeffects ...

**Comment by dittodhole** [comment] 2011-02-17 11:51
btw, you should reopen the issue, as it's still valid!

**Comment by cpauya** [comment] 2011-02-17 12:43
Good thing you found the bugs, I've been looking on those lines too but no dice.

I wanted to re-open this but cannot find the link how.  Been to GitHub's support pages but no help.

I guess I'd better create a new issue pointing here.

**Comment by cpauya** [comment] 2011-02-17 12:45
http://support.github.com/discussions/issues-issues/206-unable-to-re-open-closed-issues says I must be the repo owner or a collaborator, which I'm not.  I don't have the menu that they are talking about.

So I better create a new issue.

**Comment by themouette** [comment] 2011-02-17 17:53
this should all be fixed with last version.
enjoy :)

**Closed as completed** 2011-02-18 01:53 UTC

**Comment by cpauya** [comment] 2011-02-18 03:03
Yes, it is now fixed.  Thanks very much! :)
