### ISSUE TITLE
data binding

### ISSUE THREAD

**Issue by sureshdb** [themouette/jquery-week-calendar#115] opened 2012-01-18 12:14 UTC
i am new to use jquery week calendar.i am try to load data to calendar fro server.in this component default static data is binding using events object.so any one can help to solve my problem

**Comment by thorst** [comment] 2012-01-18 16:19
first let me say i have nothing to do with this project. Next your not reporting an issue, just that your having issues with implementing it. 

start of with the sample provided. Once you get that working substitute the static data by the data provided by your service. I set my service up to return json with the needed objects. then instead of calling the function to load static data i do a post to the service and voila everything works.

**Comment by K-Phoen** [comment] 2012-04-26 20:12
I couldn't agree more with @thorst. If you still have troubles with loading data from an external source, read the [wiki](https://github.com/themouette/jquery-week-calendar/wiki) (there is a tiny section called "Retrieving Calendar Events via a function" which shows how to load data using a non-static provisioner). And if the problem persists, the [mailing-list](https://groups.google.com/forum/?fromgroups#!forum/jquery-week-calendar) may help you.

As this is not a bug, I close this issue. Feel free to open another issue if you encounter a bug :)

**Closed as completed by K-Phoen** 2012-04-26 20:12 UTC
